// Code generated by protoc-gen-go. DO NOT EDIT.
// source: log.proto

package grpc_logging // import "istio_ecosystem/wasm_extensions/grpc_logging"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import durationpb "google.golang.org/protobuf/types/known/durationpb"
import timestamppb "google.golang.org/protobuf/types/known/timestamppb"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WriteLogRequest struct {
	LogEntries           []*WriteLogRequest_LogEntry `protobuf:"bytes,1,rep,name=log_entries,json=logEntries,proto3" json:"log_entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *WriteLogRequest) Reset()         { *m = WriteLogRequest{} }
func (m *WriteLogRequest) String() string { return proto.CompactTextString(m) }
func (*WriteLogRequest) ProtoMessage()    {}
func (*WriteLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_log_995e692a68d235a0, []int{0}
}
func (m *WriteLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteLogRequest.Unmarshal(m, b)
}
func (m *WriteLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteLogRequest.Marshal(b, m, deterministic)
}
func (dst *WriteLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteLogRequest.Merge(dst, src)
}
func (m *WriteLogRequest) XXX_Size() int {
	return xxx_messageInfo_WriteLogRequest.Size(m)
}
func (m *WriteLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteLogRequest proto.InternalMessageInfo

func (m *WriteLogRequest) GetLogEntries() []*WriteLogRequest_LogEntry {
	if m != nil {
		return m.LogEntries
	}
	return nil
}

type WriteLogRequest_LogEntry struct {
	SourceAddress        string                 `protobuf:"bytes,1,opt,name=source_address,json=sourceAddress,proto3" json:"source_address,omitempty"`
	DestinationAddress   string                 `protobuf:"bytes,2,opt,name=destination_address,json=destinationAddress,proto3" json:"destination_address,omitempty"`
	DestinationWorkload  string                 `protobuf:"bytes,3,opt,name=destination_workload,json=destinationWorkload,proto3" json:"destination_workload,omitempty"`
	DestinationNamespace string                 `protobuf:"bytes,4,opt,name=destination_namespace,json=destinationNamespace,proto3" json:"destination_namespace,omitempty"`
	Host                 string                 `protobuf:"bytes,5,opt,name=host,proto3" json:"host,omitempty"`
	Path                 string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	UserAgent            string                 `protobuf:"bytes,7,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Referer              string                 `protobuf:"bytes,8,opt,name=referer,proto3" json:"referer,omitempty"`
	RequestId            string                 `protobuf:"bytes,9,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ResponseCode         uint32                 `protobuf:"varint,12,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	Timestamp            *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Latency              *durationpb.Duration   `protobuf:"bytes,11,opt,name=latency,proto3" json:"latency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *WriteLogRequest_LogEntry) Reset()         { *m = WriteLogRequest_LogEntry{} }
func (m *WriteLogRequest_LogEntry) String() string { return proto.CompactTextString(m) }
func (*WriteLogRequest_LogEntry) ProtoMessage()    {}
func (*WriteLogRequest_LogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_log_995e692a68d235a0, []int{0, 0}
}
func (m *WriteLogRequest_LogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteLogRequest_LogEntry.Unmarshal(m, b)
}
func (m *WriteLogRequest_LogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteLogRequest_LogEntry.Marshal(b, m, deterministic)
}
func (dst *WriteLogRequest_LogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteLogRequest_LogEntry.Merge(dst, src)
}
func (m *WriteLogRequest_LogEntry) XXX_Size() int {
	return xxx_messageInfo_WriteLogRequest_LogEntry.Size(m)
}
func (m *WriteLogRequest_LogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteLogRequest_LogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_WriteLogRequest_LogEntry proto.InternalMessageInfo

func (m *WriteLogRequest_LogEntry) GetSourceAddress() string {
	if m != nil {
		return m.SourceAddress
	}
	return ""
}

func (m *WriteLogRequest_LogEntry) GetDestinationAddress() string {
	if m != nil {
		return m.DestinationAddress
	}
	return ""
}

func (m *WriteLogRequest_LogEntry) GetDestinationWorkload() string {
	if m != nil {
		return m.DestinationWorkload
	}
	return ""
}

func (m *WriteLogRequest_LogEntry) GetDestinationNamespace() string {
	if m != nil {
		return m.DestinationNamespace
	}
	return ""
}

func (m *WriteLogRequest_LogEntry) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *WriteLogRequest_LogEntry) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *WriteLogRequest_LogEntry) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *WriteLogRequest_LogEntry) GetReferer() string {
	if m != nil {
		return m.Referer
	}
	return ""
}

func (m *WriteLogRequest_LogEntry) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *WriteLogRequest_LogEntry) GetResponseCode() uint32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *WriteLogRequest_LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *WriteLogRequest_LogEntry) GetLatency() *durationpb.Duration {
	if m != nil {
		return m.Latency
	}
	return nil
}

type WriteLogResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteLogResponse) Reset()         { *m = WriteLogResponse{} }
func (m *WriteLogResponse) String() string { return proto.CompactTextString(m) }
func (*WriteLogResponse) ProtoMessage()    {}
func (*WriteLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_log_995e692a68d235a0, []int{1}
}
func (m *WriteLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteLogResponse.Unmarshal(m, b)
}
func (m *WriteLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteLogResponse.Marshal(b, m, deterministic)
}
func (dst *WriteLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteLogResponse.Merge(dst, src)
}
func (m *WriteLogResponse) XXX_Size() int {
	return xxx_messageInfo_WriteLogResponse.Size(m)
}
func (m *WriteLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WriteLogResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*WriteLogRequest)(nil), "istio_ecosystem.wasm_extensions.grpc_logging.WriteLogRequest")
	proto.RegisterType((*WriteLogRequest_LogEntry)(nil), "istio_ecosystem.wasm_extensions.grpc_logging.WriteLogRequest.LogEntry")
	proto.RegisterType((*WriteLogResponse)(nil), "istio_ecosystem.wasm_extensions.grpc_logging.WriteLogResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoggingServiceClient is the client API for LoggingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoggingServiceClient interface {
	WriteLog(ctx context.Context, in *WriteLogRequest, opts ...grpc.CallOption) (*WriteLogResponse, error)
}

type loggingServiceClient struct {
	cc *grpc.ClientConn
}

func NewLoggingServiceClient(cc *grpc.ClientConn) LoggingServiceClient {
	return &loggingServiceClient{cc}
}

func (c *loggingServiceClient) WriteLog(ctx context.Context, in *WriteLogRequest, opts ...grpc.CallOption) (*WriteLogResponse, error) {
	out := new(WriteLogResponse)
	err := c.cc.Invoke(ctx, "/istio_ecosystem.wasm_extensions.grpc_logging.LoggingService/WriteLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoggingServiceServer is the server API for LoggingService service.
type LoggingServiceServer interface {
	WriteLog(context.Context, *WriteLogRequest) (*WriteLogResponse, error)
}

func RegisterLoggingServiceServer(s *grpc.Server, srv LoggingServiceServer) {
	s.RegisterService(&_LoggingService_serviceDesc, srv)
}

func _LoggingService_WriteLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggingServiceServer).WriteLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/istio_ecosystem.wasm_extensions.grpc_logging.LoggingService/WriteLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggingServiceServer).WriteLog(ctx, req.(*WriteLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LoggingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "istio_ecosystem.wasm_extensions.grpc_logging.LoggingService",
	HandlerType: (*LoggingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteLog",
			Handler:    _LoggingService_WriteLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "log.proto",
}

func init() { proto.RegisterFile("log.proto", fileDescriptor_log_995e692a68d235a0) }

var fileDescriptor_log_995e692a68d235a0 = []byte{
	// 471 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x5f, 0x8b, 0xd3, 0x4c,
	0x14, 0xc6, 0xc9, 0xdb, 0xbe, 0xdb, 0xf6, 0x74, 0xbb, 0xca, 0xa8, 0x30, 0x16, 0xd4, 0xb2, 0x22,
	0xf4, 0x42, 0xa6, 0xd8, 0xde, 0x78, 0xa3, 0xb0, 0xfe, 0x03, 0xa1, 0x78, 0x11, 0x85, 0x05, 0x6f,
	0xc2, 0x6c, 0x72, 0x76, 0x76, 0x30, 0x9d, 0x13, 0x67, 0x26, 0xae, 0xfd, 0x08, 0x7e, 0x07, 0xbf,
	0x99, 0xe0, 0x67, 0x91, 0xcc, 0x34, 0xbb, 0xa1, 0x5e, 0xa9, 0x77, 0x93, 0xe7, 0x79, 0x7e, 0x27,
	0x67, 0xc2, 0x13, 0x18, 0x95, 0xa4, 0x44, 0x65, 0xc9, 0x13, 0x7b, 0xac, 0x9d, 0xd7, 0x94, 0x61,
	0x4e, 0x6e, 0xeb, 0x3c, 0x6e, 0xc4, 0xa5, 0x74, 0x9b, 0x0c, 0xbf, 0x7a, 0x34, 0x4e, 0x93, 0x71,
	0x42, 0xd9, 0x2a, 0xcf, 0x4a, 0x52, 0x4a, 0x1b, 0x35, 0x7d, 0xa0, 0x88, 0x54, 0x89, 0x8b, 0xc0,
	0x9e, 0xd5, 0xe7, 0x0b, 0xaf, 0x37, 0xe8, 0xbc, 0xdc, 0x54, 0x71, 0xdc, 0xf4, 0xfe, 0x7e, 0xa0,
	0xa8, 0xad, 0xf4, 0x9a, 0x4c, 0xf4, 0x8f, 0x7f, 0xf4, 0xe1, 0xc6, 0xa9, 0xd5, 0x1e, 0xd7, 0xa4,
	0x52, 0xfc, 0x5c, 0xa3, 0xf3, 0x4c, 0xc1, 0xb8, 0x24, 0x95, 0xa1, 0xf1, 0x56, 0xa3, 0xe3, 0xc9,
	0xac, 0x37, 0x1f, 0x2f, 0xdf, 0x88, 0x3f, 0x59, 0x4c, 0xec, 0xcd, 0x14, 0x6b, 0x52, 0xaf, 0x8d,
	0xb7, 0xdb, 0x14, 0xca, 0x78, 0xd2, 0xe8, 0xa6, 0x3f, 0x7b, 0x30, 0x6c, 0x0d, 0xf6, 0x08, 0x8e,
	0x1c, 0xd5, 0x36, 0xc7, 0x4c, 0x16, 0x85, 0x45, 0xd7, 0xbc, 0x38, 0x99, 0x8f, 0xd2, 0x49, 0x54,
	0x4f, 0xa2, 0xc8, 0x16, 0x70, 0xab, 0x40, 0xe7, 0xb5, 0x09, 0xb7, 0xb8, 0xca, 0xfe, 0x17, 0xb2,
	0xac, 0x63, 0xb5, 0xc0, 0x13, 0xb8, 0xdd, 0x05, 0x2e, 0xc9, 0x7e, 0x2a, 0x49, 0x16, 0xbc, 0x17,
	0x88, 0xee, 0xb0, 0xd3, 0x9d, 0xc5, 0x56, 0x70, 0xa7, 0x8b, 0x18, 0xb9, 0x41, 0x57, 0xc9, 0x1c,
	0x79, 0x3f, 0x30, 0xdd, 0x79, 0xef, 0x5a, 0x8f, 0x31, 0xe8, 0x5f, 0x90, 0xf3, 0xfc, 0xff, 0x90,
	0x09, 0xe7, 0x46, 0xab, 0xa4, 0xbf, 0xe0, 0x07, 0x51, 0x6b, 0xce, 0xec, 0x1e, 0x40, 0xed, 0xd0,
	0x66, 0x52, 0xa1, 0xf1, 0x7c, 0x10, 0x9c, 0x51, 0xa3, 0x9c, 0x34, 0x02, 0xe3, 0x30, 0xb0, 0x78,
	0x8e, 0x16, 0x2d, 0x1f, 0x06, 0xaf, 0x7d, 0x6c, 0x40, 0x1b, 0xbf, 0x66, 0xa6, 0x0b, 0x3e, 0x8a,
	0xe0, 0x4e, 0x79, 0x5b, 0xb0, 0x87, 0x30, 0xb1, 0xe8, 0x2a, 0x32, 0x0e, 0xb3, 0x9c, 0x0a, 0xe4,
	0x87, 0xb3, 0x64, 0x3e, 0x49, 0x0f, 0x5b, 0xf1, 0x25, 0x15, 0xc8, 0x9e, 0xc2, 0xe8, 0xaa, 0x21,
	0x1c, 0x66, 0xc9, 0x7c, 0xbc, 0x9c, 0x8a, 0x58, 0x11, 0xd1, 0x56, 0x44, 0x7c, 0x68, 0x13, 0xe9,
	0x75, 0x98, 0xad, 0x60, 0x50, 0x4a, 0x8f, 0x26, 0xdf, 0xf2, 0x71, 0xe0, 0xee, 0xfe, 0xc6, 0xbd,
	0xda, 0x55, 0x2b, 0x6d, 0x93, 0xc7, 0x0c, 0x6e, 0x5e, 0x17, 0x21, 0xae, 0xb1, 0xfc, 0x9e, 0xc0,
	0xd1, 0x3a, 0xb6, 0xe4, 0x3d, 0xda, 0x2f, 0x3a, 0x47, 0xf6, 0x2d, 0x81, 0x61, 0x9b, 0x63, 0xcf,
	0xfe, 0xa9, 0x68, 0xd3, 0xe7, 0x7f, 0x8b, 0xc7, 0xf5, 0x5e, 0x88, 0x8f, 0xfb, 0x7f, 0xe0, 0x62,
	0x6f, 0xc0, 0xa2, 0x3b, 0xe0, 0xec, 0x20, 0x5c, 0x7f, 0xf5, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x36,
	0x3a, 0x18, 0x94, 0xc3, 0x03, 0x00, 0x00,
}
