apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpc-logging
    version: v1
  name: grpc-logging
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-logging
  template:
    metadata:
      labels:
        app: grpc-logging
    spec:
      containers:
        - env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          image: clarechu/grpc-logging:0.1
          imagePullPolicy: Always
          name: grpc-logging
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---


apiVersion: v1
kind: Service
metadata:
  labels:
    alertmanager: main
  name: grpc-logging
  namespace: istio-system
spec:
  ports:
    - name: grpc
      port: 7575
      protocol: TCP
      targetPort: 7575
  selector:
    app: grpc-logging
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP

